#spring:
#  datasource:
#    url:jdbc:sqlite: demo.db
#    driver-class-name: org.sqlite.JDBC
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: com.enigmabridge.hibernate.dialect.SQLiteDialect
#    show-sql: true

#spring:
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
spring:
  freemarker:
    cache: false

# customer
upload:
  jar:
    filePath: c:/tmp/
