#spring:
#  datasource:
#    url:jdbc:sqlite: demo.db
#    driver-class-name: org.sqlite.JDBC
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: com.enigmabridge.hibernate.dialect.SQLiteDialect
#    show-sql: true

#spring:
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
spring:
  freemarker:
    cache: false
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/.h2/wsa
    username: sa
    password: sa
    driverClassName: org.h2.Driver

#      path: /h2-console

# customer
cxf:
  executor: c:/dev/apache-cxf-3.1.8/bin/wadl2java.bat
  javaPath: c:/tmp/src/
  customPackage: com.services
  compilerPath: c:/tmp/classes/
upload:
  jar:
    filePath: c:/tmp/
